Repository kasterism/astertower, pull requests merged in 2023-02, with the labels that each got.

#18 Add label bot
  .github/workflows/issue_label_bot.yaml
  pkg/controllers/astro_controller.go
Labels: kind/feature, size/XS

#19 Add pull bot and fix label bot
  .github/issue_label_bot.yaml
  .github/pull.yaml
Labels: size/XS

#20 Add release workflow and docker publish
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
Labels: kind/feature, size/M

#21 Add issue and pr template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yaml
Labels: size/M, kind/documentation

#22 fix bug in release
  .github/workflows/release.yaml
Labels: size/XS, kind/bug

#23 Supplement the introduction documentation for Astermule
  README.md
  docs/img/astertower.png
Labels: size/XS, kind/documentation

#25 add getting start doc, astertower-tutorial.md
  docs/img/astertower-tutorial.md
Labels: kind/documentation, size/L
